package org.menagerie.puppet_master.localisation

import org.menagerie.puppet_master.localisation.Strings.Keys
import org.menagerie.puppet_master.localisation.Strings.LocalizedStrings

object English : LocalizedStrings {
    override val strings = mapOf(
        Keys.BG_COLOR_TEXT to "BG Color",
        Keys.COLOR_MAP_CONTENT_DESCRIPTION to "Color Map",
        Keys.DRAG_TO_RESIZE_CONTENT_DESCRIPTION to "Drag to resize",
        Keys.PRESS_ANY_KEY to "Press any key...",
        Keys.NOT_ASSIGNED to "Not Assigned",
        Keys.TOGGLE to "Toggle",
        Keys.HOLD to "Hold",
        Keys.OFFLINE to "Offline",
        Keys.ONLINE to "Online",
        Keys.DIRECT to "Direct",
        Keys.STATE_MACHINE to "State Machine",
        Keys.NAME_YOUR_TROUPE_TITLE to "Name Your Troupe",
        Keys.NAME_YOUR_TROUPE_TEXT to "This is the first puppet in your troupe. Please name your troupe to continue.",
        Keys.TROUPE_NAME_LABEL to "Troupe Name",
        Keys.SAVE_BUTTON to "Save",
        Keys.ACTIVE_PUPPET_LABEL to "Active Puppet",
        Keys.NEW_PUPPET_NAME_PLACEHOLDER to "New Puppet Name",
        Keys.CREATE_BUTTON to "Create Puppet",
        Keys.LOAD_TROUPE_BUTTON to "Load Troupe",
        Keys.RENAME_TROUPE_BUTTON to "Rename Troupe",
        Keys.IMPORT_PUPPET_BUTTON to "Import Puppet",
        Keys.EXPORT_ACTIVE_PUPPET_BUTTON to "Export Active Puppet",
        Keys.CREATE_NEW_TROUPE_BUTTON to "Create New Troupe",
        Keys.RENAME_TROUPE_TITLE to "Rename Troupe",
        Keys.NEW_TROUPE_NAME_LABEL to "New Troupe Name",
        Keys.RENAME_BUTTON to "Rename",
        Keys.SERVER_CONTROLS_TITLE to "Server Controls",
        Keys.SERVER_IP_LABEL to "Server IP",
        Keys.START_SERVER_BUTTON to "Start Server",
        Keys.STOP_SERVER_BUTTON to "Stop Server",
        Keys.SPECIAL_EFFECTS_TITLE to "Special Effects",
        Keys.ADD_EFFECT_BUTTON to "Add Effect",
        Keys.DELETE_EFFECT_BUTTON to "Delete Effect",
        Keys.DISPLAY_PREVIEW_CHECKBOX to "Display Preview",
        Keys.PREVIOUS_EFFECT_BUTTON to "Previous Effect",
        Keys.NEXT_EFFECT_BUTTON to "Next Effect",
        Keys.TOGGLE_SCALE_DETAILS_BUTTON to "Toggle Scale Details",
        Keys.SCALE_SLIDER to "Scale",
        Keys.SCALE_X_SLIDER to "Scale X",
        Keys.SCALE_Y_SLIDER to "Scale Y",
        Keys.SCALE_SPEED_SLIDER to "Scale Speed",
        Keys.TOGGLE_VIBRATION_DETAILS_BUTTON to "Toggle Vibration Details",
        Keys.VIBRATION_SLIDER to "Vibration",
        Keys.VIBRATION_DISTANCE_SLIDER to "Distance",
        Keys.VIBRATION_SPEED_SLIDER to "Speed",
        Keys.GLOW_LUMINANCE_SLIDER to "Glow (Luminance)",
        Keys.SPIN_SPEED_SLIDER to "Spin Speed",
        Keys.SPIN_DIRECTION_LABEL to "Spin Direction",
        Keys.SPIN_LEFT_ICON to "Spin Left",
        Keys.SPIN_RIGHT_ICON to "Spin Right",
        Keys.PRESERVE_STATE_CHECKBOX to "Preserve this state across puppet changes",
        Keys.RENAME_BEFORE_SAVING_TEXT to "Rename Before Saving",
        Keys.NAME_MUST_BE_UNIQUE_TEXT to "Name Must Be Unique",
        Keys.ASSIGN_STATE_TITLE to "Assign State to Threshold",
        Keys.OVERWRITE_STATE_TITLE to "Overwrite State?",
        Keys.OVERWRITE_STATE_TEXT to "A state with this name already exists. Do you want to overwrite it?",
        Keys.CONNECTION_FAILED_TITLE to "Connection Failed",
        Keys.CONNECTION_FAILED_TEXT to "Could not connect to the server. Would you like to try again?",
        Keys.CANCEL_BUTTON to "Cancel",
        Keys.OVERWRITE_BUTTON to "Overwrite",
        Keys.TRY_AGAIN_BUTTON to "Try Again",
        Keys.WORK_OFFLINE_BUTTON to "Work Offline",
        Keys.GETTING_STARTED to "Create a puppet or load a troupe to get started.",
        Keys.LOAD_STATE_IMAGE to "Load a State Image.",
        Keys.CREATE_OR_SELECT_PUPPET to "Create or select a puppet to get started.",
        Keys.EYE_CONTACT_BUTTON to "Eye Contact",
        Keys.SETTINGS_BUTTON to "Settings",
        Keys.STATES_TITLE to "States",
        Keys.PUPPET_CONTROLS_BUTTON to "Puppet Controls",
        Keys.STATE_CONTROLS_BUTTON to "State Controls",
        Keys.WINDOW_TITLE to "Puppet Master",
        Keys.LOADING to "Loading...",
        Keys.APPLY to "Apply",
        Keys.NONE to "None",
        Keys.EYE_CONTACT_STUDIO_TITLE to "Eye Contact Studio",
        Keys.BACK_BUTTON_CONTENT_DESCRIPTION to "Back",
        Keys.SELECT_EYES_FROM_TROUPE_CONTENT_DESCRIPTION to "Select Eyes from Troupe",
        Keys.SELECT_A_STATE to "Select a State",
        Keys.SYNC_EYE_PARTS to "Sync Eye Parts",
        Keys.FOLLOW_CURSOR to "Follow Cursor",
        Keys.FOCUS_ON_GAME to "Focus on Game",
        Keys.CHECK_ON_AUDIENCE to "Check on Audience",
        Keys.BLINK_RATE_RANGE to "Blink Rate Range: %.2f - %.2f s",
        Keys.AUDIENCE_CHECK_RATE to "Audience Check Rate: %.2f s",
        Keys.AUDIENCE_CHECK_DURATION to "Audience Check Duration: %.2f s",
        Keys.LEFT_EYE to "Left Eye",
        Keys.RIGHT_EYE to "Right Eye",
        Keys.IRIS to "Iris",
        Keys.PUPIL to "Pupil",
        Keys.BLINK to "Blink",
        Keys.CLOSED_EYES_PREVIEW to "Closed Eyes Preview",
        Keys.SELECT_STATE_TO_BEGIN to "Select a state to begin.",
        Keys.STATE_PREVIEW_CONTENT_DESCRIPTION to "State preview",
        Keys.GAME_SCREEN to "Game Screen",
        Keys.SELECT_PART_TITLE to $$"Select %1$s",
        Keys.DRAGGABLE_CLOSED_EYE_CONTENT_DESCRIPTION to "Draggable closed eye",
        Keys.DRAGGABLE_OPEN_EYE_CONTENT_DESCRIPTION to "Draggable open eye",
        Keys.DRAGGABLE_PUPIL_CONTENT_DESCRIPTION to "Draggable pupil",
        Keys.SETTINGS_TITLE to "Settings",
        Keys.BACK to "Back",
        Keys.SERVER_IP_ADDRESS to "Server IP Address",
        Keys.START_OFFLINE to "Start Offline",
        Keys.FULLSCREEN_ON_STARTUP to "Fullscreen on Startup",
        Keys.TOGGLE_LISTEN_HOTKEY to "Toggle Listen Hotkey",
        Keys.TOGGLE_PUBLISHING_HOTKEY to "Toggle Publishing Hotkey",
        Keys.TOGGLE_ONLINE_HOTKEY to "Toggle Online Hotkey",
        Keys.CHANGE_FOCUS_HOTKEY to "Change Focus Hotkey",
        Keys.CHECK_AUDIENCE_HOTKEY to "Check Audience Hotkey",
        Keys.TOGGLE_CONTROLS_HOTKEY to "Toggle Controls Hotkey",
        Keys.SELECT_AN_EYE_SET to "Select an Eye Set",
        Keys.LIVE_PREVIEW_CONTENT_DESCRIPTION to "Live Preview",
        Keys.LEFT_PUPIL_CONTENT_DESCRIPTION to "Left Pupil",
        Keys.RIGHT_PUPIL_CONTENT_DESCRIPTION to "Right Pupil",
        Keys.CREATE_NEW_STATE to "Create New State",
        Keys.MAIN_IMAGE to "Main Image",
        Keys.SELECTED_IMAGE to "Selected Image",
        Keys.SWAP_IMAGES to "<->",
        Keys.BLINK_IMAGE to "Blink Image",
        Keys.SELECTED_BLINK_IMAGE to "Selected Blink Image",
        Keys.SELECT_IMAGES to "Select Image(s)",
        Keys.ADD_BLINKING_STATE to "Add Blinking State",
        Keys.STATE_NAME to "State Name",
        Keys.SAVE_UPDATE_STATE to "Save/Update State",
        Keys.MISSING_ERROR_MESSAGE to "Please select %1\$s to create or update a state.",
        Keys.EDIT_STATE to "Edit State: %1\$s",
        Keys.APPLIED_EFFECT to "Applied Effect: %1\$s",
        Keys.STATE_HOTKEY to "State Hotkey",
        Keys.LANGUAGE to "Language",
        Keys.STATE_GRAPH_BUTTON to "Puppeteering",
        Keys.HIGHLIGHT_ON to "Highlight",
        Keys.GET_LAYER to "Select Layer Item"
    )
}
