package org.menagerie.puppet_master.localisation

import org.menagerie.puppet_master.localisation.Strings.Keys

object French : Strings.LocalizedStrings {
        override val strings = mapOf(
            Keys.BG_COLOR_TEXT to "Couleur de fond",
            Keys.COLOR_MAP_CONTENT_DESCRIPTION to "Carte de couleurs",
            Keys.DRAG_TO_RESIZE_CONTENT_DESCRIPTION to "Faites glisser pour redimensionner",
            Keys.PRESS_ANY_KEY to "Appuyez sur n'importe quelle touche...",
            Keys.NOT_ASSIGNED to "Non attribué",
            Keys.TOGGLE to "Basculer",
            Keys.HOLD to "Maintenir",
            Keys.OFFLINE to "Hors ligne",
            Keys.ONLINE to "En ligne",
            Keys.DIRECT to "Direct",
            Keys.STATE_MACHINE to "Machine à états",
            Keys.NAME_YOUR_TROUPE_TITLE to "Nommez votre troupe",
            Keys.NAME_YOUR_TROUPE_TEXT to "Ceci est la première marionnette de votre troupe. Veuillez nommer votre troupe pour continuer.",
            Keys.TROUPE_NAME_LABEL to "Nom de la troupe",
            Keys.SAVE_BUTTON to "Enregistrer",
            Keys.ACTIVE_PUPPET_LABEL to "Marionnette active",
            Keys.NEW_PUPPET_NAME_PLACEHOLDER to "Nouveau nom de marionnette",
            Keys.CREATE_BUTTON to "Créer Marionnette",
            Keys.LOAD_TROUPE_BUTTON to "Charger la troupe",
            Keys.RENAME_TROUPE_BUTTON to "Renommer la troupe",
            Keys.IMPORT_PUPPET_BUTTON to "Importer une marionnette",
            Keys.EXPORT_ACTIVE_PUPPET_BUTTON to "Exporter la marionnette active",
            Keys.CREATE_NEW_TROUPE_BUTTON to "Créer une nouvelle troupe",
            Keys.RENAME_TROUPE_TITLE to "Renommer la troupe",
            Keys.NEW_TROUPE_NAME_LABEL to "Nouveau nom de la troupe",
            Keys.RENAME_BUTTON to "Renommer",
            Keys.SERVER_CONTROLS_TITLE to "Contrôles du serveur",
            Keys.SERVER_IP_LABEL to "IP du serveur",
            Keys.START_SERVER_BUTTON to "Démarrer le serveur",
            Keys.STOP_SERVER_BUTTON to "Arrêter le serveur",
            Keys.SPECIAL_EFFECTS_TITLE to "Effets spéciaux",
            Keys.ADD_EFFECT_BUTTON to "Ajouter un effet",
            Keys.DELETE_EFFECT_BUTTON to "Supprimer l'effet",
            Keys.DISPLAY_PREVIEW_CHECKBOX to "Afficher l'aperçu",
            Keys.PREVIOUS_EFFECT_BUTTON to "Effet précédent",
            Keys.NEXT_EFFECT_BUTTON to "Effet suivant",
            Keys.TOGGLE_SCALE_DETAILS_BUTTON to "Basculer les détails de l'échelle",
            Keys.SCALE_SLIDER to "Échelle",
            Keys.SCALE_X_SLIDER to "Échelle X",
            Keys.SCALE_Y_SLIDER to "Échelle Y",
            Keys.SCALE_SPEED_SLIDER to "Vitesse de l'échelle",
            Keys.TOGGLE_VIBRATION_DETAILS_BUTTON to "Basculer les détails de la vibration",
            Keys.VIBRATION_SLIDER to "Vibration",
            Keys.VIBRATION_DISTANCE_SLIDER to "Distance",
            Keys.VIBRATION_SPEED_SLIDER to "Vitesse",
            Keys.GLOW_LUMINANCE_SLIDER to "Lueur (Luminance)",
            Keys.SPIN_SPEED_SLIDER to "Vitesse de rotation",
            Keys.SPIN_DIRECTION_LABEL to "Sens de rotation",
            Keys.SPIN_LEFT_ICON to "Rotation à gauche",
            Keys.SPIN_RIGHT_ICON to "Rotation à droite",
            Keys.PRESERVE_STATE_CHECKBOX to "Préserver cet état lors des changements de marionnette",
            Keys.RENAME_BEFORE_SAVING_TEXT to "Renommer avant d'enregistrer",
            Keys.NAME_MUST_BE_UNIQUE_TEXT to "Le nom doit être unique",
            Keys.ASSIGN_STATE_TITLE to "Attribuer un état au seuil",
            Keys.OVERWRITE_STATE_TITLE to "Écraser l'état?",
            Keys.OVERWRITE_STATE_TEXT to "Un état avec ce nom existe déjà. Voulez-vous l'écraser?",
            Keys.CONNECTION_FAILED_TITLE to "Échec de la connexion",
            Keys.CONNECTION_FAILED_TEXT to "Impossible de se connecter au serveur. Voulez-vous réessayer?",
            Keys.CANCEL_BUTTON to "Annuler",
            Keys.OVERWRITE_BUTTON to "Écraser",
            Keys.TRY_AGAIN_BUTTON to "Réessayer",
            Keys.WORK_OFFLINE_BUTTON to "Travailler hors ligne",
            Keys.GETTING_STARTED to "Créez une marionnette ou chargez une troupe pour commencer.",
            Keys.LOAD_STATE_IMAGE to "Charger une image d'état.",
            Keys.CREATE_OR_SELECT_PUPPET to "Créez ou sélectionnez une marionnette pour commencer.",
            Keys.EYE_CONTACT_BUTTON to "Contact visuel",
            Keys.SETTINGS_BUTTON to "Paramètres",
            Keys.STATES_TITLE to "États",
            Keys.PUPPET_CONTROLS_BUTTON to "Contrôles de marionnettes",
            Keys.STATE_CONTROLS_BUTTON to "Contrôles d'état",
            Keys.WINDOW_TITLE to "Puppet Master",
            Keys.LOADING to "Chargement...",
            Keys.APPLY to "Appliquer",
            Keys.NONE to "Aucun",
            Keys.EYE_CONTACT_STUDIO_TITLE to "Studio de Contact Visuel",
            Keys.BACK_BUTTON_CONTENT_DESCRIPTION to "Retour",
            Keys.SELECT_EYES_FROM_TROUPE_CONTENT_DESCRIPTION to "Sélectionner les yeux de la troupe",
            Keys.SELECT_A_STATE to "Sélectionnez un état",
            Keys.SYNC_EYE_PARTS to "Synchroniser les parties de l'œil",
            Keys.FOLLOW_CURSOR to "Suivre le curseur",
            Keys.FOCUS_ON_GAME to "Focus sur le jeu",
            Keys.CHECK_ON_AUDIENCE to "Vérifier le public",
            Keys.BLINK_RATE_RANGE to "Plage de clignement: %1\$d - %2\$d ms",
            Keys.AUDIENCE_CHECK_RATE to "Taux de vérification de l'audience: %1\$d ms",
            Keys.AUDIENCE_CHECK_DURATION to "Durée de la vérification de l'audience: %1\$d ms",
            Keys.LEFT_EYE to "Œil gauche",
            Keys.RIGHT_EYE to "Œil droit",
            Keys.IRIS to "Iris",
            Keys.PUPIL to "Pupille",
            Keys.BLINK to "Clignement",
            Keys.CLOSED_EYES_PREVIEW to "Aperçu des yeux fermés",
            Keys.SELECT_STATE_TO_BEGIN to "Sélectionnez un état pour commencer.",
            Keys.STATE_PREVIEW_CONTENT_DESCRIPTION to "Aperçu de l'état",
            Keys.GAME_SCREEN to "Écran de jeu",
            Keys.SELECT_PART_TITLE to "Sélectionner %1\$s",
            Keys.DRAGGABLE_CLOSED_EYE_CONTENT_DESCRIPTION to "Œil fermé déplaçable",
            Keys.DRAGGABLE_OPEN_EYE_CONTENT_DESCRIPTION to "Œil ouvert déplaçable",
            Keys.DRAGGABLE_PUPIL_CONTENT_DESCRIPTION to "Pupille déplaçable",
            Keys.SETTINGS_TITLE to "Paramètres",
            Keys.BACK to "Retour",
            Keys.SERVER_IP_ADDRESS to "Adresse IP du serveur",
            Keys.START_OFFLINE to "Démarrer hors ligne",
            Keys.FULLSCREEN_ON_STARTUP to "Plein écran au démarrage",
            Keys.TOGGLE_LISTEN_HOTKEY to "Raccourci pour basculer l'écoute",
            Keys.TOGGLE_PUBLISHING_HOTKEY to "Raccourci pour basculer la publication",
            Keys.TOGGLE_ONLINE_HOTKEY to "Raccourci pour basculer en ligne",
            Keys.CHANGE_FOCUS_HOTKEY to "Raccourci pour changer le focus",
            Keys.CHECK_AUDIENCE_HOTKEY to "Raccourci pour vérifier l'audience",
            Keys.TOGGLE_CONTROLS_HOTKEY to "Raccourci pour basculer les contrôles",
            Keys.SELECT_AN_EYE_SET to "Sélectionnez un ensemble d'yeux",
            Keys.LIVE_PREVIEW_CONTENT_DESCRIPTION to "Aperçu en direct",
            Keys.LEFT_PUPIL_CONTENT_DESCRIPTION to "Pupille gauche",
            Keys.RIGHT_PUPIL_CONTENT_DESCRIPTION to "Pupille droite",
            Keys.CREATE_NEW_STATE to "Créer un nouvel état",
            Keys.MAIN_IMAGE to "Image principale",
            Keys.SELECTED_IMAGE to "Image sélectionnée",
            Keys.SWAP_IMAGES to "<->",
            Keys.BLINK_IMAGE to "Image clignotante",
            Keys.SELECTED_BLINK_IMAGE to "Image clignotante sélectionnée",
            Keys.SELECT_IMAGES to "Sélectionner une ou plusieurs images",
            Keys.ADD_BLINKING_STATE to "Ajouter un état de clignement",
            Keys.STATE_NAME to "Nom de l'état",
            Keys.SAVE_UPDATE_STATE to "Enregistrer/Mettre à jour l'état",
            Keys.MISSING_ERROR_MESSAGE to "Veuillez sélectionner %1\$s pour créer ou mettre à jour un état.",
            Keys.EDIT_STATE to "Modifier l'état: %1\$s",
            Keys.APPLIED_EFFECT to "Effet appliqué: %1\$s",
            Keys.STATE_HOTKEY to "Raccourci d'état",
            Keys.LANGUAGE to "Langue",
            Keys.STATE_GRAPH_BUTTON to "TRANSLATION DATA ERROR"
        )
    }