package org.menagerie.puppet_master.localisation

import org.menagerie.puppet_master.localisation.Strings.Keys
import org.menagerie.puppet_master.localisation.Strings.LocalizedStrings

object Pirate : LocalizedStrings {
    override val strings = mapOf(
        Keys.BG_COLOR_TEXT to "Deck's Hue",
        Keys.COLOR_MAP_CONTENT_DESCRIPTION to "Chart o' Hues",
        Keys.DRAG_TO_RESIZE_CONTENT_DESCRIPTION to "Heave to resize",
        Keys.PRESS_ANY_KEY to "Smash any key...",
        Keys.NOT_ASSIGNED to "Not Claimed",
        Keys.TOGGLE to "Switcharoo",
        Keys.HOLD to "Hold Fast",
        Keys.OFFLINE to "Landlubber",
        Keys.ONLINE to "At Sea",
        Keys.DIRECT to "Straight Command",
        Keys.STATE_MACHINE to "Puppet's Dance",
        Keys.NAME_YOUR_TROUPE_TITLE to "Name Yer Crew",
        Keys.NAME_YOUR_TROUPE_TEXT to "This be the first puppet in yer crew. Give yer crew a name to continue.",
        Keys.TROUPE_NAME_LABEL to "Crew Name",
        Keys.SAVE_BUTTON to "Remember",
        Keys.ACTIVE_PUPPET_LABEL to "First Mate",
        Keys.NEW_PUPPET_NAME_PLACEHOLDER to "New Puppet Name",
        Keys.CREATE_BUTTON to "Craft Puppet",
        Keys.LOAD_TROUPE_BUTTON to "Load Crew",
        Keys.RENAME_TROUPE_BUTTON to "Rename Crew",
        Keys.IMPORT_PUPPET_BUTTON to "Import Puppet",
        Keys.EXPORT_ACTIVE_PUPPET_BUTTON to "Export Active Puppet",
        Keys.CREATE_NEW_TROUPE_BUTTON to "Hire New Crew",
        Keys.RENAME_TROUPE_TITLE to "Rename Crew",
        Keys.NEW_TROUPE_NAME_LABEL to "New Crew Name",
        Keys.RENAME_BUTTON to "Rename",
        Keys.SERVER_CONTROLS_TITLE to "Port Controls",
        Keys.SERVER_IP_LABEL to "Where Be Port?",
        Keys.START_SERVER_BUTTON to "Make Port",
        Keys.STOP_SERVER_BUTTON to "Leave Port",
        Keys.SPECIAL_EFFECTS_TITLE to "Wicked Magic",
        Keys.ADD_EFFECT_BUTTON to "Brew Effect",
        Keys.DELETE_EFFECT_BUTTON to "Curse Effect",
        Keys.DISPLAY_PREVIEW_CHECKBOX to "Gaze Upon Preview",
        Keys.PREVIOUS_EFFECT_BUTTON to "Previous Witchery",
        Keys.NEXT_EFFECT_BUTTON to "Next Witchery",
        Keys.TOGGLE_SCALE_DETAILS_BUTTON to "Toggle Scale Details",
        Keys.SCALE_SLIDER to "Scale",
        Keys.SCALE_X_SLIDER to "Scale X",
        Keys.SCALE_Y_SLIDER to "Scale Y",
        Keys.SCALE_SPEED_SLIDER to "Scale Speed",
        Keys.TOGGLE_VIBRATION_DETAILS_BUTTON to "Toggle Vibration Details",
        Keys.VIBRATION_SLIDER to "Vibration",
        Keys.VIBRATION_DISTANCE_SLIDER to "Distance",
        Keys.VIBRATION_SPEED_SLIDER to "Speed",
        Keys.GLOW_LUMINANCE_SLIDER to "Luminant Glow",
        Keys.SPIN_SPEED_SLIDER to "Roll Speed",
        Keys.SPIN_DIRECTION_LABEL to "Roll Direction",
        Keys.SPIN_LEFT_ICON to "Roll Left",
        Keys.SPIN_RIGHT_ICON to "Roll Right",
        Keys.PRESERVE_STATE_CHECKBOX to "Preserve this magic across puppet changes",
        Keys.RENAME_BEFORE_SAVING_TEXT to "Rename Before Savin'",
        Keys.NAME_MUST_BE_UNIQUE_TEXT to "Name Must Be Unique, Matey",
        Keys.ASSIGN_STATE_TITLE to "Mark Yer Spot",
        Keys.OVERWRITE_STATE_TITLE to "Overwrite Yer State?",
        Keys.OVERWRITE_STATE_TEXT to "A state with this name already be claimed. D'ye want to send it to Davy Jones' Locker?",
        Keys.CONNECTION_FAILED_TITLE to "Connection Scuttled",
        Keys.CONNECTION_FAILED_TEXT to "Couldn't make port. Heave ho and try again?",
        Keys.CANCEL_BUTTON to "Belay That",
        Keys.OVERWRITE_BUTTON to "Overwrite",
        Keys.TRY_AGAIN_BUTTON to "Heave Ho!",
        Keys.WORK_OFFLINE_BUTTON to "Go it Alone",
        Keys.GETTING_STARTED to "Craft a puppet or gather a crew t' get started.",
        Keys.LOAD_STATE_IMAGE to "Hoist a State Image.",
        Keys.CREATE_OR_SELECT_PUPPET to "Craft or pick a puppet t' get started.",
        Keys.EYE_CONTACT_BUTTON to "Meet Yer Gaze",
        Keys.SETTINGS_BUTTON to "Ship's Orders",
        Keys.STATES_TITLE to "States o' Being",
        Keys.PUPPET_CONTROLS_BUTTON to "Puppet Ropes",
        Keys.STATE_CONTROLS_BUTTON to "State Ropes",
        Keys.WINDOW_TITLE to "Master O' Puppets",
        Keys.LOADING to "Settin' Sail...",
        Keys.APPLY to "Aye!",
        Keys.NONE to "None",
        Keys.EYE_CONTACT_STUDIO_TITLE to "Eye Contact Studio",
        Keys.BACK_BUTTON_CONTENT_DESCRIPTION to "Avast",
        Keys.SELECT_EYES_FROM_TROUPE_CONTENT_DESCRIPTION to "Plunder Eyes from the Crew",
        Keys.SELECT_A_STATE to "Pick a State o' Being",
        Keys.SYNC_EYE_PARTS to "No Eye Patch For You",
        Keys.FOLLOW_CURSOR to "Follow the Pointy Thing",
        Keys.FOCUS_ON_GAME to "Eyes on the Horizon",
        Keys.CHECK_ON_AUDIENCE to "Check on the Scurvy Dogs",
        Keys.BLINK_RATE_RANGE to "Blindin' o' the Sun: %1\$d - %2\$d ms",
        Keys.AUDIENCE_CHECK_RATE to "Audience Spyin' Rate: %1\$d ms",
        Keys.AUDIENCE_CHECK_DURATION to "Audience Spyin' Duration: %1\$d ms",
        Keys.LEFT_EYE to "Port Eye",
        Keys.RIGHT_EYE to "Starboard Eye",
        Keys.IRIS to "Iris",
        Keys.PUPIL to "Pupil",
        Keys.BLINK to "Blink",
        Keys.CLOSED_EYES_PREVIEW to "Closed Eyes Preview",
        Keys.SELECT_STATE_TO_BEGIN to "Select a state to begin, matey.",
        Keys.STATE_PREVIEW_CONTENT_DESCRIPTION to "State preview",
        Keys.GAME_SCREEN to "Game Porthole",
        Keys.SELECT_PART_TITLE to "Select %1\$s",
        Keys.DRAGGABLE_CLOSED_EYE_CONTENT_DESCRIPTION to "Draggable closed eye",
        Keys.DRAGGABLE_OPEN_EYE_CONTENT_DESCRIPTION to "Draggable open eye",
        Keys.DRAGGABLE_PUPIL_CONTENT_DESCRIPTION to "Draggable pupil",
        Keys.SETTINGS_TITLE to "Ship's Orders",
        Keys.BACK to "Avast",
        Keys.SERVER_IP_ADDRESS to "Where Be Port?",
        Keys.START_OFFLINE to "Go It Alone",
        Keys.FULLSCREEN_ON_STARTUP to "Full Sail at Sunrise",
        Keys.TOGGLE_LISTEN_HOTKEY to "Toggle Ears Hotkey",
        Keys.TOGGLE_PUBLISHING_HOTKEY to "Toggle Parrot Hotkey",
        Keys.TOGGLE_ONLINE_HOTKEY to "Toggle Sea Rover Hotkey",
        Keys.CHANGE_FOCUS_HOTKEY to "Change Gaze Hotkey",
        Keys.CHECK_AUDIENCE_HOTKEY to "Check Scurvy Dogs Hotkey",
        Keys.TOGGLE_CONTROLS_HOTKEY to "Toggle Ropes Hotkey",
        Keys.SELECT_AN_EYE_SET to "Choose a Pair o' Peepers",
        Keys.LIVE_PREVIEW_CONTENT_DESCRIPTION to "Live Preview",
        Keys.LEFT_PUPIL_CONTENT_DESCRIPTION to "Portside Pupil",
        Keys.RIGHT_PUPIL_CONTENT_DESCRIPTION to "Starboard Pupil",
        Keys.CREATE_NEW_STATE to "Craft New State",
        Keys.MAIN_IMAGE to "Ship's Figurehead",
        Keys.SELECTED_IMAGE to "Selected Figurehead",
        Keys.SWAP_IMAGES to "<->",
        Keys.BLINK_IMAGE to "Winkin' Figurehead",
        Keys.SELECTED_BLINK_IMAGE to "Selected Winkin' Figurehead",
        Keys.SELECT_IMAGES to "Choose Yer Colors",
        Keys.ADD_BLINKING_STATE to "Add Winkin' State",
        Keys.STATE_NAME to "State Name",
        Keys.SAVE_UPDATE_STATE to "Save/Update State",
        Keys.MISSING_ERROR_MESSAGE to "Ahoy! Choose %1\$s to craft or update a state.",
        Keys.EDIT_STATE to "Edit State: %1\$s",
        Keys.APPLIED_EFFECT to "Applied Effect: %1\$s",
        Keys.STATE_HOTKEY to "State Hotkey",
        Keys.LANGUAGE to "Tongue",
        Keys.STATE_GRAPH_BUTTON to "Make 'em Dance"
    )
}